name: Trigger auto deployment for voosh-db-mcp-internal

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/voosh-db-mcp-internal-AutoDeployTrigger-23f99aff-2231-4cb6-a359-451552baa305.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VOOSHDBMCPINTERNAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VOOSHDBMCPINTERNAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VOOSHDBMCPINTERNAL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: caa0d9111382acr.azurecr.io
          registryUsername: ${{ secrets.VOOSHDBMCPINTERNAL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VOOSHDBMCPINTERNAL_REGISTRY_PASSWORD }}
          containerAppName: voosh-db-mcp-internal
          resourceGroup: VOOSH-PRODUCTS-EAST-US2
          imageToBuild: caa0d9111382acr.azurecr.io/voosh-db-mcp-internal:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


